<?php

namespace Database\Seeders;

use App\Models\Post;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $posts = [
            [
                'title' => 'How I Review Pull Requests Effectively',
                'description' => 'Sharing my personal experience after spending years in this field. The lessons I learned the hard way so you do not have to repeat the same costly mistakes that I made.',
                'status' => 'published',
                'post_type' => 'Thread',
                'views' => 20114,
                'likes' => 1528,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tips for Better Work Life Balance in Tech',
                'description' => 'A deep dive that covers every important angle of this topic in detail. Bookmark it share it with your team and come back to it whenever you need a thorough refresher on the subject.',
                'status' => 'published',
                'post_type' => 'Twitter',
                'views' => 18978,
                'likes' => 970,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Morning Routine of a Productive Dev',
                'description' => 'A deep dive that covers every important angle of this topic in detail. Bookmark it share it with your team and come back to it whenever you need a thorough refresher on the subject.',
                'status' => 'draft',
                'post_type' => 'News',
                'views' => 85,
                'likes' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'AI Tools That Saved Me Hours This Week',
                'description' => 'Sharing my personal experience after spending years in this field. The lessons I learned the hard way so you do not have to repeat the same costly mistakes that I made.',
                'status' => 'archived',
                'post_type' => 'News',
                'views' => 46330,
                'likes' => 918,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How to Ace Technical Interviews',
                'description' => 'Deep diving into the technical details so you understand not just the how but the why behind every decision. Understanding the fundamentals truly makes everything else click into place.',
                'status' => 'published',
                'post_type' => 'News',
                'views' => 30121,
                'likes' => 1021,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Why I Love Working with the Laravel Framework',
                'description' => 'This content resonated with thousands of readers for a very good reason. The insights here are simple but incredibly powerful and most people in our industry are completely ignoring them.',
                'status' => 'published',
                'post_type' => 'Twitter',
                'views' => 15979,
                'likes' => 960,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'My Stack for Building MVPs Really Fast',
                'description' => 'Breaking down complex concepts into simple digestible pieces. Whether you are a beginner or an experienced professional there is something valuable here for everyone who reads it.',
                'status' => 'published',
                'post_type' => 'Blog',
                'views' => 27805,
                'likes' => 3708,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'End of Year Developer Wrap-Up 2024',
                'description' => 'Sharing the exact workflow and tools that helped me save multiple hours every single week. You can realistically implement all of this by the end of today if you follow the steps.',
                'status' => 'published',
                'post_type' => 'Article',
                'views' => 30169,
                'likes' => 2111,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Future of Web Development',
                'description' => 'A behind-the-scenes look at how I approach this topic professionally every day. From initial planning all the way to final execution everything important is covered in careful detail.',
                'status' => 'draft',
                'post_type' => 'Blog',
                'views' => 177,
                'likes' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Building Your Own Simple CDN',
                'description' => 'Deep diving into the technical details so you understand not just the how but the why behind every decision. Understanding the fundamentals truly makes everything else click into place.',
                'status' => 'draft',
                'post_type' => 'News',
                'views' => 183,
                'likes' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How I Wrote 30 Blog Posts in a Single Month',
                'description' => 'This approach completely transformed how I work on a daily basis. Once you see it in action for yourself you will genuinely wonder how you ever managed to get things done without it.',
                'status' => 'draft',
                'post_type' => 'Linkedin',
                'views' => 377,
                'likes' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Problem with Tutorial Hell',
                'description' => 'This post covers the most practical techniques I have used in real production environments. Real-world examples included with full code snippets you can actually use starting today.',
                'status' => 'published',
                'post_type' => 'Thread',
                'views' => 20698,
                'likes' => 367,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Monolith vs Microservices: Real Talk',
                'description' => 'Sharing the exact workflow and tools that helped me save multiple hours every single week. You can realistically implement all of this by the end of today if you follow the steps.',
                'status' => 'published',
                'post_type' => 'Thread',
                'views' => 24600,
                'likes' => 363,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Understanding the JavaScript Event Loop',
                'description' => 'This content resonated with thousands of readers for a very good reason. The insights here are simple but incredibly powerful and most people in our industry are completely ignoring them.',
                'status' => 'draft',
                'post_type' => 'Thread',
                'views' => 23451,
                'likes' => 7103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Stop Overcomplicating Your Code',
                'description' => 'Sharing my personal experience after spending years in this field. The lessons I learned the hard way so you do not have to repeat the same costly mistakes that I made.',
                'status' => 'draft',
                'post_type' => 'TikTok',
                'views' => 218869,
                'likes' => 26831,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'My Thoughts on AI Replacing Developers',
                'description' => 'An honest comparison based on actual project experience over several years. I lay out the pros cons and exact scenarios where one approach clearly beats the other in practice.',
                'status' => 'published',
                'post_type' => 'Blog',
                'views' => 12371,
                'likes' => 4145,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Web Accessibility: The Most Forgotten Skill',
                'description' => 'After months of research and real-world testing here is what actually works in practice. Forget the hype — this is the raw unfiltered truth from someone who has genuinely done it.',
                'status' => 'draft',
                'post_type' => 'Blog',
                'views' => 42,
                'likes' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Getting Started with Docker Containers',
                'description' => 'Step-by-step guide with clear examples throughout. Follow along and you will have a fully working implementation by the time you reach the very end of this detailed walkthrough.',
                'status' => 'archived',
                'post_type' => 'Linkedin',
                'views' => 47230,
                'likes' => 363,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Passive Income Through Digital Products',
                'description' => 'A deep dive that covers every important angle of this topic in detail. Bookmark it share it with your team and come back to it whenever you need a thorough refresher on the subject.',
                'status' => 'published',
                'post_type' => 'Facebook',
                'views' => 18680,
                'likes' => 1750,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Design Patterns Every Developer Should Know',
                'description' => 'A deep dive that covers every important angle of this topic in detail. Bookmark it share it with your team and come back to it whenever you need a thorough refresher on the subject.',
                'status' => 'published',
                'post_type' => 'Article',
                'views' => 26917,
                'likes' => 857,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Stripe Integration Step by Step Tutorial',
                'description' => 'After months of research and real-world testing here is what actually works in practice. Forget the hype — this is the raw unfiltered truth from someone who has genuinely done it.',
                'status' => 'draft',
                'post_type' => 'Instagram',
                'views' => 217950,
                'likes' => 43306,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Solo Founder Journey Month 3 Update',
                'description' => 'A deep dive that covers every important angle of this topic in detail. Bookmark it share it with your team and come back to it whenever you need a thorough refresher on the subject.',
                'status' => 'published',
                'post_type' => 'Facebook',
                'views' => 646,
                'likes' => 1245,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Chrome Extensions Every Developer Needs',
                'description' => 'This content resonated with thousands of readers for a very good reason. The insights here are simple but incredibly powerful and most people in our industry are completely ignoring them.',
                'status' => 'published',
                'post_type' => 'Tutorial',
                'views' => 45376,
                'likes' => 1125,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Breaking Into Tech with No Degree',
                'description' => 'Step-by-step guide with clear examples throughout. Follow along and you will have a fully working implementation by the time you reach the very end of this detailed walkthrough.',
                'status' => 'published',
                'post_type' => 'Instagram',
                'views' => 80502,
                'likes' => 34659,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How I Landed a 120k Dev Job',
                'description' => 'Breaking down complex concepts into simple digestible pieces. Whether you are a beginner or an experienced professional there is something valuable here for everyone who reads it.',
                'status' => 'draft',
                'post_type' => 'Facebook',
                'views' => 128,
                'likes' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kubernetes for Beginners',
                'description' => 'Breaking down complex concepts into simple digestible pieces. Whether you are a beginner or an experienced professional there is something valuable here for everyone who reads it.',
                'status' => 'draft',
                'post_type' => 'Twitter',
                'views' => 22177,
                'likes' => 5791,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Database Design Fundamentals',
                'description' => 'A deep dive that covers every important angle of this topic in detail. Bookmark it share it with your team and come back to it whenever you need a thorough refresher on the subject.',
                'status' => 'published',
                'post_type' => 'Tutorial',
                'views' => 32557,
                'likes' => 2779,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How Open Source Changed My Career',
                'description' => 'Sharing the exact workflow and tools that helped me save multiple hours every single week. You can realistically implement all of this by the end of today if you follow the steps.',
                'status' => 'archived',
                'post_type' => 'Instagram',
                'views' => 194039,
                'likes' => 20415,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'My First Open Source Contribution',
                'description' => 'This content resonated with thousands of readers for a very good reason. The insights here are simple but incredibly powerful and most people in our industry are completely ignoring them.',
                'status' => 'archived',
                'post_type' => 'News',
                'views' => 11116,
                'likes' => 4440,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tailwind CSS: A Complete Guide',
                'description' => 'Sharing my personal experience after spending years in this field. The lessons I learned the hard way so you do not have to repeat the same costly mistakes that I made.',
                'status' => 'draft',
                'post_type' => 'Facebook',
                'views' => 367,
                'likes' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SaaS vs One-Time Products: My Personal Take',
                'description' => 'The community asked for this content repeatedly. I compiled the most common questions and answered them all in one place with practical actionable advice drawn from real experience.',
                'status' => 'draft',
                'post_type' => 'Instagram',
                'views' => 98015,
                'likes' => 36847,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Art of Writing Clean Code',
                'description' => 'Deep diving into the technical details so you understand not just the how but the why behind every decision. Understanding the fundamentals truly makes everything else click into place.',
                'status' => 'published',
                'post_type' => 'Tutorial',
                'views' => 39518,
                'likes' => 4037,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Scaling Your Backend to Millions of Users',
                'description' => 'A deep dive that covers every important angle of this topic in detail. Bookmark it share it with your team and come back to it whenever you need a thorough refresher on the subject.',
                'status' => 'published',
                'post_type' => 'Instagram',
                'views' => 245959,
                'likes' => 5302,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'New Framework Just Dropped and It Is Amazing',
                'description' => 'This content resonated with thousands of readers for a very good reason. The insights here are simple but incredibly powerful and most people in our industry are completely ignoring them.',
                'status' => 'published',
                'post_type' => 'Twitter',
                'views' => 22702,
                'likes' => 6437,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Behind My LinkedIn Content Strategy',
                'description' => 'This content resonated with thousands of readers for a very good reason. The insights here are simple but incredibly powerful and most people in our industry are completely ignoring them.',
                'status' => 'archived',
                'post_type' => 'News',
                'views' => 12001,
                'likes' => 788,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How I Built My First SaaS Product',
                'description' => 'A behind-the-scenes look at how I approach this topic professionally every day. From initial planning all the way to final execution everything important is covered in careful detail.',
                'status' => 'published',
                'post_type' => 'Instagram',
                'views' => 130807,
                'likes' => 47209,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How to Read Documentation Effectively',
                'description' => 'Deep diving into the technical details so you understand not just the how but the why behind every decision. Understanding the fundamentals truly makes everything else click into place.',
                'status' => 'draft',
                'post_type' => 'Facebook',
                'views' => 377,
                'likes' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Why Every Developer Should Learn SQL',
                'description' => 'Step-by-step guide with clear examples throughout. Follow along and you will have a fully working implementation by the time you reach the very end of this detailed walkthrough.',
                'status' => 'published',
                'post_type' => 'Linkedin',
                'views' => 11856,
                'likes' => 379,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'My Biggest Coding Mistake and What I Learned',
                'description' => 'An honest comparison based on actual project experience over several years. I lay out the pros cons and exact scenarios where one approach clearly beats the other in practice.',
                'status' => 'archived',
                'post_type' => 'Blog',
                'views' => 48390,
                'likes' => 3601,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Building a Real-Time Chat App',
                'description' => 'Step-by-step guide with clear examples throughout. Follow along and you will have a fully working implementation by the time you reach the very end of this detailed walkthrough.',
                'status' => 'draft',
                'post_type' => 'News',
                'views' => 380,
                'likes' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Unit Testing with PHPUnit',
                'description' => 'The community asked for this content repeatedly. I compiled the most common questions and answered them all in one place with practical actionable advice drawn from real experience.',
                'status' => 'draft',
                'post_type' => 'Thread',
                'views' => 3164,
                'likes' => 7493,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'GraphQL vs REST: Which One to Choose',
                'description' => 'Step-by-step guide with clear examples throughout. Follow along and you will have a fully working implementation by the time you reach the very end of this detailed walkthrough.',
                'status' => 'published',
                'post_type' => 'Linkedin',
                'views' => 24726,
                'likes' => 4977,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'WebSockets vs Server-Sent Events Explained',
                'description' => 'A comprehensive walkthrough covering everything from setup to deployment. Perfect for beginners who want to get hands-on experience and build something real by the end of this guide.',
                'status' => 'draft',
                'post_type' => 'Tutorial',
                'views' => 443,
                'likes' => 49,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Python for Data Science Beginners',
                'description' => 'This content resonated with thousands of readers for a very good reason. The insights here are simple but incredibly powerful and most people in our industry are completely ignoring them.',
                'status' => 'published',
                'post_type' => 'Blog',
                'views' => 34010,
                'likes' => 759,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SEO Tips Every Developer Should Know',
                'description' => 'Step-by-step guide with clear examples throughout. Follow along and you will have a fully working implementation by the time you reach the very end of this detailed walkthrough.',
                'status' => 'draft',
                'post_type' => 'Linkedin',
                'views' => 432,
                'likes' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Building a Second Brain as a Developer',
                'description' => 'Step-by-step guide with clear examples throughout. Follow along and you will have a fully working implementation by the time you reach the very end of this detailed walkthrough.',
                'status' => 'draft',
                'post_type' => 'Tutorial',
                'views' => 302,
                'likes' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Vue.js vs React: 2024 Comparison',
                'description' => 'My completely honest take after using this approach in three different production projects at scale. I cover the good the bad and what I would absolutely do differently the next time.',
                'status' => 'published',
                'post_type' => 'Facebook',
                'views' => 30284,
                'likes' => 4582,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How I Use AI to Write Code 3x Faster',
                'description' => 'This content resonated with thousands of readers for a very good reason. The insights here are simple but incredibly powerful and most people in our industry are completely ignoring them.',
                'status' => 'published',
                'post_type' => 'Article',
                'views' => 1931,
                'likes' => 881,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Building Mobile Apps with React Native',
                'description' => 'My completely honest take after using this approach in three different production projects at scale. I cover the good the bad and what I would absolutely do differently the next time.',
                'status' => 'published',
                'post_type' => 'Facebook',
                'views' => 47655,
                'likes' => 4126,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'CSS Grid vs Flexbox: A Deep Dive',
                'description' => 'A behind-the-scenes look at how I approach this topic professionally every day. From initial planning all the way to final execution everything important is covered in careful detail.',
                'status' => 'draft',
                'post_type' => 'Twitter',
                'views' => 25355,
                'likes' => 5932,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'This TikTok Blew Up Overnight',
                'description' => 'My completely honest take after using this approach in three different production projects at scale. I cover the good the bad and what I would absolutely do differently the next time.',
                'status' => 'draft',
                'post_type' => 'Instagram',
                'views' => 85430,
                'likes' => 18974,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How I Automate My Social Media Entirely',
                'description' => 'This post covers the most practical techniques I have used in real production environments. Real-world examples included with full code snippets you can actually use starting today.',
                'status' => 'published',
                'post_type' => 'Article',
                'views' => 31986,
                'likes' => 3834,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How I Grew My Twitter Following to 50k',
                'description' => 'This approach completely transformed how I work on a daily basis. Once you see it in action for yourself you will genuinely wonder how you ever managed to get things done without it.',
                'status' => 'draft',
                'post_type' => 'Article',
                'views' => 438,
                'likes' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'What Nobody Tells You About Freelancing',
                'description' => 'A deep dive that covers every important angle of this topic in detail. Bookmark it share it with your team and come back to it whenever you need a thorough refresher on the subject.',
                'status' => 'draft',
                'post_type' => 'Facebook',
                'views' => 333,
                'likes' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Why Code Reviews Matter More Than You Think',
                'description' => 'Deep diving into the technical details so you understand not just the how but the why behind every decision. Understanding the fundamentals truly makes everything else click into place.',
                'status' => 'draft',
                'post_type' => 'Instagram',
                'views' => 190371,
                'likes' => 43899,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How to Build a Personal Brand as a Developer',
                'description' => 'A comprehensive walkthrough covering everything from setup to deployment. Perfect for beginners who want to get hands-on experience and build something real by the end of this guide.',
                'status' => 'published',
                'post_type' => 'TikTok',
                'views' => 77206,
                'likes' => 15083,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dark Mode Design Best Practices',
                'description' => 'A comprehensive walkthrough covering everything from setup to deployment. Perfect for beginners who want to get hands-on experience and build something real by the end of this guide.',
                'status' => 'published',
                'post_type' => 'Thread',
                'views' => 21859,
                'likes' => 4716,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How to Handle Imposter Syndrome as a Dev',
                'description' => 'Sharing the exact workflow and tools that helped me save multiple hours every single week. You can realistically implement all of this by the end of today if you follow the steps.',
                'status' => 'draft',
                'post_type' => 'TikTok',
                'views' => 170343,
                'likes' => 44874,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Thread: Lessons from 5 Failed Startup Attempts',
                'description' => 'After months of research and real-world testing here is what actually works in practice. Forget the hype — this is the raw unfiltered truth from someone who has genuinely done it.',
                'status' => 'published',
                'post_type' => 'Facebook',
                'views' => 8778,
                'likes' => 2053,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Thread: How We Hit 10k Monthly Recurring Revenue',
                'description' => 'Step-by-step guide with clear examples throughout. Follow along and you will have a fully working implementation by the time you reach the very end of this detailed walkthrough.',
                'status' => 'published',
                'post_type' => 'Instagram',
                'views' => 109809,
                'likes' => 35604,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tools I Use Every Single Day',
                'description' => 'Deep diving into the technical details so you understand not just the how but the why behind every decision. Understanding the fundamentals truly makes everything else click into place.',
                'status' => 'published',
                'post_type' => 'TikTok',
                'views' => 147648,
                'likes' => 20717,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Redis Caching Strategies Explained',
                'description' => 'Sharing the exact workflow and tools that helped me save multiple hours every single week. You can realistically implement all of this by the end of today if you follow the steps.',
                'status' => 'draft',
                'post_type' => 'Blog',
                'views' => 187,
                'likes' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'From Junior to Senior Developer in 2 Years',
                'description' => 'The community asked for this content repeatedly. I compiled the most common questions and answered them all in one place with practical actionable advice drawn from real experience.',
                'status' => 'draft',
                'post_type' => 'Thread',
                'views' => 5186,
                'likes' => 5997,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Building in Public: What I Learned',
                'description' => 'This approach completely transformed how I work on a daily basis. Once you see it in action for yourself you will genuinely wonder how you ever managed to get things done without it.',
                'status' => 'draft',
                'post_type' => 'Article',
                'views' => 130,
                'likes' => 49,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Understanding OAuth 2.0 in Simple Terms',
                'description' => 'The community asked for this content repeatedly. I compiled the most common questions and answered them all in one place with practical actionable advice drawn from real experience.',
                'status' => 'published',
                'post_type' => 'Tutorial',
                'views' => 20767,
                'likes' => 3110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Building CLI Tools with Node.js',
                'description' => 'A deep dive that covers every important angle of this topic in detail. Bookmark it share it with your team and come back to it whenever you need a thorough refresher on the subject.',
                'status' => 'published',
                'post_type' => 'Tutorial',
                'views' => 11471,
                'likes' => 3738,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'My Side Project Finally Made Money',
                'description' => 'After months of research and real-world testing here is what actually works in practice. Forget the hype — this is the raw unfiltered truth from someone who has genuinely done it.',
                'status' => 'archived',
                'post_type' => 'Instagram',
                'views' => 235228,
                'likes' => 14683,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Ultimate Guide to Webhooks',
                'description' => 'A comprehensive walkthrough covering everything from setup to deployment. Perfect for beginners who want to get hands-on experience and build something real by the end of this guide.',
                'status' => 'published',
                'post_type' => 'News',
                'views' => 29400,
                'likes' => 3229,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'My Viral Facebook Post Full Breakdown',
                'description' => 'My completely honest take after using this approach in three different production projects at scale. I cover the good the bad and what I would absolutely do differently the next time.',
                'status' => 'published',
                'post_type' => 'Instagram',
                'views' => 62117,
                'likes' => 37438,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mastering Git Branching Strategies',
                'description' => 'Sharing my personal experience after spending years in this field. The lessons I learned the hard way so you do not have to repeat the same costly mistakes that I made.',
                'status' => 'draft',
                'post_type' => 'Blog',
                'views' => 394,
                'likes' => 49,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Email Marketing Strategies for Developers',
                'description' => 'This approach completely transformed how I work on a daily basis. Once you see it in action for yourself you will genuinely wonder how you ever managed to get things done without it.',
                'status' => 'published',
                'post_type' => 'Linkedin',
                'views' => 26888,
                'likes' => 3616,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How I Got 10k LinkedIn Followers Organically',
                'description' => 'The community asked for this content repeatedly. I compiled the most common questions and answered them all in one place with practical actionable advice drawn from real experience.',
                'status' => 'draft',
                'post_type' => 'Linkedin',
                'views' => 37,
                'likes' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Understanding SOLID Principles in Practice',
                'description' => 'A deep dive that covers every important angle of this topic in detail. Bookmark it share it with your team and come back to it whenever you need a thorough refresher on the subject.',
                'status' => 'published',
                'post_type' => 'Tutorial',
                'views' => 42420,
                'likes' => 1836,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Launching a Product with Zero Budget',
                'description' => 'Deep diving into the technical details so you understand not just the how but the why behind every decision. Understanding the fundamentals truly makes everything else click into place.',
                'status' => 'draft',
                'post_type' => 'Instagram',
                'views' => 198434,
                'likes' => 31519,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Truth About 10x Developers',
                'description' => 'This approach completely transformed how I work on a daily basis. Once you see it in action for yourself you will genuinely wonder how you ever managed to get things done without it.',
                'status' => 'archived',
                'post_type' => 'Twitter',
                'views' => 15031,
                'likes' => 1725,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'DevOps Best Practices for 2024',
                'description' => 'Deep diving into the technical details so you understand not just the how but the why behind every decision. Understanding the fundamentals truly makes everything else click into place.',
                'status' => 'published',
                'post_type' => 'Thread',
                'views' => 22998,
                'likes' => 4779,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Working Remotely as a Developer',
                'description' => 'The community asked for this content repeatedly. I compiled the most common questions and answered them all in one place with practical actionable advice drawn from real experience.',
                'status' => 'archived',
                'post_type' => 'Thread',
                'views' => 13928,
                'likes' => 4712,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Deploying Laravel Applications to AWS',
                'description' => 'Sharing the exact workflow and tools that helped me save multiple hours every single week. You can realistically implement all of this by the end of today if you follow the steps.',
                'status' => 'draft',
                'post_type' => 'Thread',
                'views' => 12922,
                'likes' => 1978,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Introduction to TypeScript',
                'description' => 'A behind-the-scenes look at how I approach this topic professionally every day. From initial planning all the way to final execution everything important is covered in careful detail.',
                'status' => 'published',
                'post_type' => 'Linkedin',
                'views' => 6733,
                'likes' => 364,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'TikTok Content Strategy for Tech Creators',
                'description' => 'A deep dive that covers every important angle of this topic in detail. Bookmark it share it with your team and come back to it whenever you need a thorough refresher on the subject.',
                'status' => 'draft',
                'post_type' => 'Facebook',
                'views' => 465,
                'likes' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Understanding JWT Authentication',
                'description' => 'Step-by-step guide with clear examples throughout. Follow along and you will have a fully working implementation by the time you reach the very end of this detailed walkthrough.',
                'status' => 'draft',
                'post_type' => 'Twitter',
                'views' => 7384,
                'likes' => 7049,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Vim vs VS Code: My Final Answer',
                'description' => 'An honest comparison based on actual project experience over several years. I lay out the pros cons and exact scenarios where one approach clearly beats the other in practice.',
                'status' => 'published',
                'post_type' => 'Facebook',
                'views' => 9984,
                'likes' => 3876,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Instagram Growth Strategy That Actually Works',
                'description' => 'This post covers the most practical techniques I have used in real production environments. Real-world examples included with full code snippets you can actually use starting today.',
                'status' => 'draft',
                'post_type' => 'Thread',
                'views' => 16806,
                'likes' => 5093,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Building a Portfolio That Actually Gets Noticed',
                'description' => 'A behind-the-scenes look at how I approach this topic professionally every day. From initial planning all the way to final execution everything important is covered in careful detail.',
                'status' => 'published',
                'post_type' => 'News',
                'views' => 5123,
                'likes' => 2075,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How I Use Notion for Project Management',
                'description' => 'This approach completely transformed how I work on a daily basis. Once you see it in action for yourself you will genuinely wonder how you ever managed to get things done without it.',
                'status' => 'draft',
                'post_type' => 'Linkedin',
                'views' => 294,
                'likes' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hot Take: Agile is Completely Broken',
                'description' => 'Sharing my personal experience after spending years in this field. The lessons I learned the hard way so you do not have to repeat the same costly mistakes that I made.',
                'status' => 'draft',
                'post_type' => 'Twitter',
                'views' => 16189,
                'likes' => 3082,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Deploying Applications with GitHub Actions',
                'description' => 'Deep diving into the technical details so you understand not just the how but the why behind every decision. Understanding the fundamentals truly makes everything else click into place.',
                'status' => 'published',
                'post_type' => 'TikTok',
                'views' => 63269,
                'likes' => 42304,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Why I Quit My Job to Go Freelance',
                'description' => 'Deep diving into the technical details so you understand not just the how but the why behind every decision. Understanding the fundamentals truly makes everything else click into place.',
                'status' => 'archived',
                'post_type' => 'News',
                'views' => 1605,
                'likes' => 4799,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Async Await vs Promises in JavaScript',
                'description' => 'A comprehensive walkthrough covering everything from setup to deployment. Perfect for beginners who want to get hands-on experience and build something real by the end of this guide.',
                'status' => 'draft',
                'post_type' => 'TikTok',
                'views' => 100745,
                'likes' => 36403,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'My Top 5 Productivity Apps for Developers',
                'description' => 'After months of research and real-world testing here is what actually works in practice. Forget the hype — this is the raw unfiltered truth from someone who has genuinely done it.',
                'status' => 'published',
                'post_type' => 'Twitter',
                'views' => 22945,
                'likes' => 3140,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Why I Switched from React to Vue',
                'description' => 'An honest comparison based on actual project experience over several years. I lay out the pros cons and exact scenarios where one approach clearly beats the other in practice.',
                'status' => 'draft',
                'post_type' => 'Facebook',
                'views' => 56,
                'likes' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Best Coding YouTube Channels Right Now',
                'description' => 'An honest comparison based on actual project experience over several years. I lay out the pros cons and exact scenarios where one approach clearly beats the other in practice.',
                'status' => 'draft',
                'post_type' => 'Linkedin',
                'views' => 131,
                'likes' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Building Microservices Architecture',
                'description' => 'After months of research and real-world testing here is what actually works in practice. Forget the hype — this is the raw unfiltered truth from someone who has genuinely done it.',
                'status' => 'published',
                'post_type' => 'TikTok',
                'views' => 181631,
                'likes' => 29563,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Building a Newsletter from Absolute Scratch',
                'description' => 'My completely honest take after using this approach in three different production projects at scale. I cover the good the bad and what I would absolutely do differently the next time.',
                'status' => 'published',
                'post_type' => 'News',
                'views' => 43793,
                'likes' => 3431,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'My First Year as a Freelance Developer',
                'description' => 'This content resonated with thousands of readers for a very good reason. The insights here are simple but incredibly powerful and most people in our industry are completely ignoring them.',
                'status' => 'draft',
                'post_type' => 'Blog',
                'views' => 274,
                'likes' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Understanding Browser Storage Options',
                'description' => 'This post covers the most practical techniques I have used in real production environments. Real-world examples included with full code snippets you can actually use starting today.',
                'status' => 'published',
                'post_type' => 'Linkedin',
                'views' => 15156,
                'likes' => 1468,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How I Organize All My Code Projects',
                'description' => 'Deep diving into the technical details so you understand not just the how but the why behind every decision. Understanding the fundamentals truly makes everything else click into place.',
                'status' => 'draft',
                'post_type' => 'Instagram',
                'views' => 243622,
                'likes' => 36669,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Why I Read One Technical Book Per Month',
                'description' => 'An honest comparison based on actual project experience over several years. I lay out the pros cons and exact scenarios where one approach clearly beats the other in practice.',
                'status' => 'published',
                'post_type' => 'Tutorial',
                'views' => 35026,
                'likes' => 4572,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How to Write Better Commit Messages',
                'description' => 'This post covers the most practical techniques I have used in real production environments. Real-world examples included with full code snippets you can actually use starting today.',
                'status' => 'published',
                'post_type' => 'Linkedin',
                'views' => 44962,
                'likes' => 810,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How to Build REST APIs with Node.js',
                'description' => 'A comprehensive walkthrough covering everything from setup to deployment. Perfect for beginners who want to get hands-on experience and build something real by the end of this guide.',
                'status' => 'published',
                'post_type' => 'Instagram',
                'views' => 89347,
                'likes' => 43823,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Post::insert($posts);
    }
}
